import os
from dotenv import load_dotenv
from supabase import create_client

# Load environment variables
load_dotenv()

# Initialize Supabase client
supabase = create_client(
    os.getenv("SUPABASE_URL"),
    os.getenv("SUPABASE_KEY")
)

# SQL for creating the documents table (vector store)
documents_table = """
create table if not exists documents (
    id bigint generated by default as identity primary key,
    content text,
    metadata jsonb,
    embedding vector(1536)
);

create index if not exists documents_embedding_idx
on documents
using ivfflat (embedding vector_cosine_ops)
with (lists = 100);
"""

# SQL for creating the chat history table
chat_history_table = """
create table if not exists chat_history (
    id bigint generated by default as identity primary key,
    content text not null,
    speaker_id text not null,
    timestamp timestamptz default now(),
    metadata jsonb default '{}'::jsonb
);

create index if not exists chat_history_speaker_idx on chat_history(speaker_id);
create index if not exists chat_history_timestamp_idx on chat_history(timestamp);
"""

def init_database():
    """Initialize the database tables."""
    try:
        # Create tables
        supabase.query(documents_table).execute()
        supabase.query(chat_history_table).execute()
        
        print("Successfully created database tables!")
        
    except Exception as e:
        print(f"Error creating tables: {str(e)}")

if __name__ == "__main__":
    init_database() 